# Assuming the all 3 services will be built and run separately by developer
# Also, expecting future improvements to be updated in the README file
services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=editor
      - POSTGRESQL_USERNAME=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    env_file:
      - ./backend/.env  # <--- load environment variables from here
    environment:
      - DB_URL=postgresql://postgres:password123@postgresql:5432/editor?schema=public
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/notes"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    